import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Terms of Service — Parsli",
  description: "Terms and conditions for using the Parsli document extraction service.",
  alternates: {
    canonical: "https://parsli.co/terms",
  },
}

export default function TermsOfServicePage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16 prose prose-neutral dark:prose-invert">
      <h1>Terms of Service</h1>
      <p className="text-sm text-muted-foreground">Last updated: 7 March 2026</p>

      <p>
        These Terms of Service (&quot;Terms&quot;) govern your access to and use of the Parsli document
        extraction service (&quot;Service&quot;) provided by BYTEBEAMAGENCY LTD (&quot;Parsli&quot;,
        &quot;we&quot;, &quot;us&quot;, &quot;our&quot;), a company registered in England and Wales.
      </p>
      <p>
        By creating an account or using the Service, you agree to be bound by these Terms. If you do not
        agree, do not use the Service.
      </p>

      <h2>1. Definitions</h2>
      <ul>
        <li><strong>&quot;Customer&quot;</strong> — the individual or entity that registers for and uses the Service.</li>
        <li><strong>&quot;Customer Data&quot;</strong> — all documents, files, and data uploaded to or generated by the Service on behalf of the Customer.</li>
        <li><strong>&quot;Authorised Users&quot;</strong> — individuals permitted by the Customer to use the Service under the Customer&apos;s account.</li>
        <li><strong>&quot;Subscription&quot;</strong> — the paid or free plan selected by the Customer.</li>
      </ul>

      <h2>2. Service Description</h2>
      <p>
        Parsli provides AI-powered document extraction. Customers upload documents, configure extraction
        schemas, and receive structured data. The Service includes a web application, API, webhook
        integrations, and email inbox processing.
      </p>

      <h2>3. Account Registration</h2>
      <ul>
        <li>You must provide accurate and complete registration information.</li>
        <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
        <li>You must notify us immediately of any unauthorised use of your account.</li>
        <li>You must be at least 18 years of age to use the Service.</li>
      </ul>

      <h2>4. Licence to Use</h2>
      <p>
        We grant you a non-exclusive, non-transferable, revocable licence to access and use the Service
        for your internal business operations, subject to these Terms and your Subscription plan.
      </p>
      <p>You may not:</p>
      <ul>
        <li>Sublicence, resell, or redistribute the Service or access to it.</li>
        <li>Reverse engineer, decompile, or disassemble any part of the Service.</li>
        <li>Use the Service to build a competing product.</li>
        <li>Remove or modify any proprietary notices.</li>
      </ul>

      <h2>5. Intellectual Property</h2>
      <ul>
        <li>
          <strong>Our IP</strong> — Parsli and its licensors retain all rights in the Service,
          including software, algorithms, design, trademarks, and documentation.
        </li>
        <li>
          <strong>Your data</strong> — You retain all ownership rights in your Customer Data.
          We claim no intellectual property rights over documents you upload or extraction results
          generated from your data.
        </li>
        <li>
          <strong>Feedback</strong> — If you provide suggestions or feedback about the Service,
          you grant us a non-exclusive, royalty-free, perpetual licence to use that feedback to
          improve the Service.
        </li>
      </ul>

      <h2>6. Subscriptions, Fees and Payment</h2>
      <h3>Plans and pricing</h3>
      <p>
        The Service is offered in multiple tiers (Free, Starter, Growth, Pro, Business) with
        different usage limits and features. Current pricing is available at{" "}
        <a href="https://parsli.co/pricing">parsli.co/pricing</a>.
      </p>
      <h3>Billing</h3>
      <ul>
        <li>Paid Subscriptions are billed monthly or annually in advance via Stripe.</li>
        <li>All fees are quoted in US Dollars (USD) and are exclusive of applicable taxes.</li>
        <li>You authorise us to charge your payment method on file for recurring Subscription fees.</li>
      </ul>
      <h3>Usage limits</h3>
      <ul>
        <li>Each plan includes a monthly page allocation. Usage resets at the start of each billing period.</li>
        <li>If you exceed your page allocation, extraction requests will be rejected until the next billing period or until you upgrade.</li>
      </ul>
      <h3>Refunds</h3>
      <p>
        Subscription fees are non-refundable except where required by applicable law. If you cancel
        mid-cycle, you retain access until the end of your current billing period.
      </p>
      <h3>Price changes</h3>
      <p>
        We may adjust pricing with 30 days&apos; written notice. Your continued use of a paid
        Subscription after the effective date constitutes acceptance of the new pricing.
      </p>

      <h2>7. Data Processing</h2>
      <ul>
        <li>
          You are the <strong>data controller</strong> for Customer Data. We act as a{" "}
          <strong>data processor</strong> on your behalf.
        </li>
        <li>
          We process Customer Data solely to provide the Service. We do not access, use, or share
          your documents for any purpose beyond delivering extraction results.
        </li>
        <li>
          <strong>We do not use your documents to train AI models.</strong> Document content is sent
          to our LLM provider for real-time extraction only and is not retained by them for training.
        </li>
        <li>
          Our privacy practices are described in our{" "}
          <a href="/privacy">Privacy Policy</a>.
        </li>
      </ul>

      <h2>8. Acceptable Use</h2>
      <p>You agree not to use the Service to:</p>
      <ul>
        <li>Upload malicious files, malware, or content designed to exploit the Service.</li>
        <li>Process documents containing illegal content.</li>
        <li>Circumvent usage limits, rate limits, or security measures.</li>
        <li>Send spam or unsolicited communications via the Service.</li>
        <li>Impersonate another person or entity.</li>
        <li>Interfere with or disrupt the Service or its infrastructure.</li>
        <li>Use the Service for any high-risk application where failure could lead to
          death, personal injury, or significant environmental damage.</li>
      </ul>
      <p>
        We reserve the right to suspend or terminate your account immediately if you violate
        this Acceptable Use policy.
      </p>

      <h2>9. Availability and Support</h2>
      <ul>
        <li>
          We aim to maintain high availability but do not guarantee uninterrupted or error-free
          operation. The Service is provided on an &quot;as is&quot; and &quot;as available&quot; basis.
        </li>
        <li>We may perform scheduled maintenance with reasonable advance notice where possible.</li>
        <li>
          Support is provided via email at{" "}
          <a href="mailto:talal@bytebeam.co">talal@bytebeam.co</a>. Response times
          vary by plan tier.
        </li>
      </ul>

      <h2>10. Confidentiality</h2>
      <p>
        Each party agrees to keep confidential any non-public information received from the other
        party, and to use such information only for the purposes of this agreement. This obligation
        does not apply to information that is publicly available, independently developed, or
        required to be disclosed by law.
      </p>

      <h2>11. Warranties and Disclaimers</h2>
      <ul>
        <li>
          We warrant that the Service will be provided with reasonable skill and care consistent
          with industry standards.
        </li>
        <li>
          <strong>Except as expressly stated</strong>, the Service is provided &quot;as is&quot;
          without warranties of any kind, whether express, implied, or statutory, including
          warranties of merchantability, fitness for a particular purpose, or non-infringement.
        </li>
        <li>
          We do not warrant that extraction results will be 100% accurate. AI-powered extraction
          is probabilistic by nature, and you are responsible for reviewing results.
        </li>
      </ul>

      <h2>12. Limitation of Liability</h2>
      <ul>
        <li>
          To the maximum extent permitted by law, our total aggregate liability arising from or
          relating to these Terms shall not exceed the fees paid by you in the 12 months
          preceding the claim.
        </li>
        <li>
          We shall not be liable for any indirect, incidental, special, consequential, or punitive
          damages, including loss of profits, data, or business opportunities.
        </li>
        <li>
          Nothing in these Terms excludes or limits liability for death or personal injury caused
          by negligence, fraud, or any other liability that cannot be excluded by law.
        </li>
      </ul>

      <h2>13. Indemnification</h2>
      <ul>
        <li>
          <strong>By us</strong> — We will indemnify you against third-party claims alleging that
          the Service infringes their intellectual property rights, provided you notify us promptly
          and allow us to control the defence.
        </li>
        <li>
          <strong>By you</strong> — You will indemnify us against third-party claims arising from
          your Customer Data, your use of the Service in violation of these Terms, or your breach
          of applicable law.
        </li>
      </ul>

      <h2>14. Term and Termination</h2>
      <ul>
        <li>
          <strong>Free plans</strong> — may be terminated by either party at any time.
        </li>
        <li>
          <strong>Paid plans</strong> — renew automatically. You may cancel at any time through
          the billing portal; access continues until the end of the current billing period.
        </li>
        <li>
          We may terminate or suspend your account immediately for material breach of these Terms,
          including violation of the Acceptable Use policy.
        </li>
        <li>
          Upon termination, you may export your data within 30 days. After that period,
          we will delete your Customer Data in accordance with our Privacy Policy.
        </li>
      </ul>

      <h2>15. Force Majeure</h2>
      <p>
        Neither party shall be liable for delays or failures in performance resulting from causes
        beyond its reasonable control, including natural disasters, war, terrorism, pandemics,
        government actions, power failures, or internet disruptions.
      </p>

      <h2>16. Assignment</h2>
      <p>
        You may not assign these Terms without our prior written consent. We may assign these Terms
        to an affiliate or in connection with a merger, acquisition, or sale of assets, provided
        that the assignee agrees to be bound by these Terms.
      </p>

      <h2>17. Changes to These Terms</h2>
      <p>
        We may modify these Terms with 30 days&apos; written notice via email or a notice on the
        Service. Material changes will be highlighted. Your continued use of the Service after the
        effective date constitutes acceptance.
      </p>

      <h2>18. Governing Law and Disputes</h2>
      <p>
        These Terms are governed by the laws of England and Wales. Any disputes shall first be
        attempted to be resolved through good-faith negotiation. If unresolved within 30 days,
        disputes shall be submitted to the exclusive jurisdiction of the courts of England and Wales.
      </p>

      <h2>19. Miscellaneous</h2>
      <ul>
        <li>These Terms constitute the entire agreement between you and Parsli regarding the Service.</li>
        <li>If any provision is held invalid, the remaining provisions continue in full force.</li>
        <li>Our failure to enforce any right does not constitute a waiver of that right.</li>
        <li>The parties are independent contractors; nothing creates a partnership or agency relationship.</li>
      </ul>

      <h2>20. Contact</h2>
      <p>
        BYTEBEAMAGENCY LTD<br />
        Email: <a href="mailto:talal@bytebeam.co">talal@bytebeam.co</a><br />
        Website: <a href="https://parsli.co">parsli.co</a>
      </p>
    </div>
  )
}
